=== mbizhani/Devolcano/src/main/resources/devolcano-metadata.dtd
<?xml version="1.0" encoding="UTF-8"?>

		<!ELEMENT meta (filterClass|classes)*>
		<!ELEMENT filterClass (#PCDATA)>
		<!ELEMENT classes (class)*>
		<!ELEMENT class (cinfo|id|fields)*>
		<!ATTLIST class
				fqn CDATA #REQUIRED>
		<!ELEMENT cinfo (#PCDATA)>
		<!ATTLIST cinfo
				ignore (true|false)
				hasForm (true|false)
				hasAdd (true|false)
				hasList (true|false)
				hasFVO (true|false)
				>
		<!ELEMENT id (#PCDATA)>
		<!ATTLIST id
				ref CDATA #REQUIRED>
		<!ELEMENT fields (field)*>
		<!ATTLIST field
				name CDATA #REQUIRED>
		<!ELEMENT field (finfo)*>
		<!ELEMENT finfo (#PCDATA|htmlAttr?)>
		<!ATTLIST finfo
				ignore (true|false)
				hasForm (true|false)
				hasList (true|false)
				hasFVO (true|false)
				listType (simple|search)
				hasTimePart (true|false)
				required (true|false)
				textType (simple|multiline|richtext|code)
				codeType (XML|SQL|PL_SQL|MS_SQL|MY_SQL|GROOVY)
				>
		<!ELEMENT htmlAttr (#PCDATA)>

=== mbizhani/Devolcano/dlava/Metadata.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE meta PUBLIC
		"Meta Data"
		"http://www.devocative.org/dtd/devolcano-metadata.dtd">

<meta>
	<filterClass>targetClass.entity</filterClass>
	<classes>
		<class fqn="org.devocative.devolcano.test.entity.Person">
			<cinfo/>
			<id ref="id"/>
			<fields>
				<field name="id">
					<finfo/>
				</field>
				<field name="name">
					<finfo/>
				</field>
				<field name="birthDate">
					<finfo/>
				</field>
				<field name="books">
					<finfo required="true"/>
				</field>
				<field name="weight">
					<finfo hasForm="false" hasFVO="false"/>
				</field>
			</fields>
		</class>
		<class fqn="org.devocative.devolcano.test.entity.Book">
			<cinfo/>
			<id ref="id"/>
			<fields>
				<field name="id">
					<finfo/>
				</field>
				<field name="name">
					<finfo/>
				</field>
				<field name="description">
					<finfo textType="multiline">
						<htmlAttr>cols=&quot;40&quot; rows=&quot;10&quot;</htmlAttr>
					</finfo>
				</field>
				<field name="sampleCode">
					<finfo textType="code" codeType="XML"/>
				</field>
				<field name="author">
					<finfo/>
				</field>
				<field name="publishYear">
					<finfo/>
				</field>
				<field name="bookType">
					<finfo/>
				</field>
			</fields>
		</class>
	</classes>
</meta>
