=== mbizhani/Devolcano/src/main/resources/devolcano-plan.dtd
<?xml version="1.0" encoding="UTF-8"?>

		<!ELEMENT plan (packageMap|volcanoes)>
		<!ELEMENT packageMap (from)+>
		<!ELEMENT from (to)+>
		<!ATTLIST from
				pkg CDATA #REQUIRED
				includePattern CDATA
				excludePattern CDATA
				ignore (true|false)
				includeSubPackages (true|false) >
		<!ELEMENT to (#PCDATA)>
		<!ATTLIST to
				pkgReplace CDATA #REQUIRED
				generatorRef CDATA #REQUIRED
				genDir CDATA #REQUIRED
				ignore (true|false)>
		<!ELEMENT volcanoes (volcano)+>
		<!ELEMENT volcano (precondition|template)>
		<!ATTLIST volcano
				name CDATA #REQUIRED>
		<!ELEMENT precondition (#PCDATA)>
		<!ELEMENT template (overwriteCheckString)?>
		<!ATTLIST template
				file CDATA #REQUIRED
				genFileType CDATA #REQUIRED
				overwrite (check|force)
				prefix CDATA
				suffix CDATA>
		<!ELEMENT overwriteCheckString (#PCDATA)>

=== mbizhani/Devolcano/dlaval/Plan.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plan PUBLIC
		"Plan"
		"http://www.devocative.org/dtd/devolcano-plan.dtd">

<plan>
	<packageMap>
		<!-- includePattern="in" excludePattern="ex" -->
		<from pkg="org.devocative.devolcano.test.entity" includeSubPackages="false">
			<to pkgReplace="entity:vo" generatorRef="LVO" genDir="src/test/java"/>
			<!--<to pkgReplace="temp" generatorRef="LVO" genDir="src" />-->
		</from>
	</packageMap>

	<volcanoes>
		<volcano name="LVO">
			<precondition>
				<![CDATA[
				targetClass.normal && targetClass.ok
				]]>
			</precondition>

			<template file="/templates/Test.gsp"
					  prefix="Oops" suffix="LVO"
					  genFileType="java"
					  overwrite="check">
				<overwriteCheckString>//overwrite</overwriteCheckString>
			</template>
		</volcano>
	</volcanoes>

</plan>
